### PR TITLE
Add FLUFFY to ptr

### PR DESCRIPTION
**Pull request by ghost**
Hello guys,
I am doing it for the first time in my life (pull request on GitHub) so I kindly ask for understanding. I will correct any errors if there are any, just let me know.
I am opening a second one, since I have to change the icon from square to circle and upadte the icon IPFS location path.
Thank you in advance!

### CODE REVIEW

**Comment by ghost** [comment]
Hello guys,
Any update on this?

**Comment by kiok46** [comment]
Hi @fluffybch Thanks for the PR, there is an extra `}` at the end, could you please make sure that the json is valid(You can check online for json validators)?
I'll merge this as soon as it's fixed.

Thanks

**Comment by ghost** [comment]
Hello kiok46,
I apologize for this mistake it is now corrected. 
I checked the file using https://jsonlint.com/ and it is shown as valid.

**Comment by ghost** [comment]
Thanks! :-)

**Pull request merged**
